#!/bin/bash
set -e

# === Paths ===
INDEX_FILE="index.sh"
UTILS_DIR="utils"
LIB_DIR="lib"
OUTPUT_FILE="install.sh"

# Appends a file to OUTPUT_FILE, stripping the shebang line only if present
append_file() {
  local file="$1"
  if [ -f "$file" ]; then
    echo "" >> "$OUTPUT_FILE"
    if head -n 1 "$file" | grep -q '^#!'; then
      tail -n +2 "$file" >> "$OUTPUT_FILE"
    else
      cat "$file" >> "$OUTPUT_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
  fi
}

# Recursively appends all .sh files under a directory, in sorted order
append_dir_recursive() {
  local dir="$1"
  if [ -d "$dir" ]; then
    while IFS= read -r -d '' file; do
      append_file "$file"
    done < <(find "$dir" -type f -name '*.sh' -print0 | sort -z)
  else
    echo "⚠️  $dir/ directory not found"
  fi
}

# Start fresh
cat > "$OUTPUT_FILE" << 'EOT'
#!/bin/bash
set -e

# This script is generated by build.sh. Do not edit directly.

EOT

# === Inline all lib/**/*.sh ===
append_dir_recursive "$LIB_DIR"

# === Inline all utils/**/*.sh ===
append_dir_recursive "$UTILS_DIR"

# === Add main index.sh (skip shebang if present) ===
append_file "$INDEX_FILE"

chmod +x "$OUTPUT_FILE"

echo "Done."
ls -lh "$OUTPUT_FILE"
