#!/bin/bash
set -e

# === Paths ===
INDEX_FILE="index.sh"
UTILS_DIR="utils"
LIB_DIR="lib"
OUTPUT_FILE="install.sh"

# Appends a file to OUTPUT_FILE, stripping the shebang line only if present
append_file() {
  local file="$1"
  if [ -f "$file" ]; then
    echo "" >> "$OUTPUT_FILE"
    if head -n 1 "$file" | grep -q '^#!'; then
      tail -n +2 "$file" >> "$OUTPUT_FILE"
    else
      cat "$file" >> "$OUTPUT_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
  fi
}

# Start fresh
cat > "$OUTPUT_FILE" << 'EOT'
#!/bin/bash
set -e

# This script is generated by build.sh. Do not edit directly.

EOT

# === Inline all lib/*.sh ===
if [ -d "$LIB_DIR" ]; then
  for file in "$LIB_DIR"/*.sh; do
    append_file "$file"
  done
else
  echo "⚠️  $LIB_DIR/ directory not found"
fi

# === Inline all utils/*.sh ===
if [ -d "$UTILS_DIR" ]; then
  for file in "$UTILS_DIR"/*.sh; do
    append_file "$file"
  done
else
  echo "⚠️  $UTILS_DIR/ directory not found"
fi

# === Add main index.sh (skip shebang if present) ===
append_file "$INDEX_FILE"

chmod +x "$OUTPUT_FILE"

echo "Done."
ls -lh "$OUTPUT_FILE"