#!/bin/bash
set -e

# This script is generated by build.sh. Do not edit directly.


packages=(
  sudo
  git
  curl
  btop
  fastfetch
)

desktop_packages=(
  gnome-session
  gnome-shell
  gdm3
  gvfs
  gvfs-backends
  network-manager-gnome
  nautilus
  gnome-terminal
  gnome-tweaks
  gnome-text-editor
  gnome-system-monitor
  xdg-desktop-portal-gnome
  fonts-cantarell
)

other_packages=(
  [node]='wget -qO- https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs'
  [bun]='wget -qO- --show-progress https://bun.sh/install | bash'
  [docker]='wget -qO- https://get.docker.com | sudo sh && sudo usermod -aG docker "$USER"'
)

other_desktop_packages=(
  [brave]='curl -fsS https://dl.brave.com/install.sh | sh'
)


install_packages() {
  logger info "Installing must-have packages..."
  apt install -y "${packages[@]}"
}

install_other_packages() {
  logger info "Installing other must-have packages..."
  for package in "${!other_packages[@]}"; do
    local install_function="${other_packages[$package]}"
    if ! command -v "$package" &> /dev/null; then
      logger info "Installing $package..."
      $install_function || logger error "Failed to install $package"
    else
      logger done "$package is already installed."
    fi
  done
}

install_desktop_packages() {
  if [[ "$INSTALL_DESKTOP" == "y" ]]; then
    logger info "Installing desktop packages..."
    apt install -y --no-install-recommends "${desktop_packages[@]}"
  else
    logger info "Skipping desktop install."
  fi
}

install_other_desktop_packages() {
  if [[ "$INSTALL_DESKTOP" == "y" ]]; then
    logger info "Installing other desktop packages..."
    for package in "${!other_desktop_packages[@]}"; do
      local install_cmd="${other_desktop_packages[$package]}"
      if ! command -v "$package" &> /dev/null; then
        logger info "Installing $package..."
        eval "$install_cmd" || logger error "Failed to install $package"
      else
        logger done "$package is already installed."
      fi
    done
  else
    logger info "Skipping other desktop packages install."
  fi
}


is_running_as_root || { logger error "Run this script as root (or via su -c)."; exit 1; }

logger info "Starting installation script..."
confirm "Install minimal desktop apps (GNOME + Brave)?" && INSTALL_DESKTOP="y" || INSTALL_DESKTOP="n"
apt update
install_packages
setup_fastfetch
setup_sudoers "$(get_real_user)"
install_desktop_packages
logger done "Done."
confirm "Reboot now?" "Y" && sudo reboot now || logger info "Reboot later to apply changes."

