#!/bin/bash
set -e

# This script is generated by build.sh. Do not edit directly.


must_have_packages=(
  sudo
  git
  curl
  btop
  fastfetch
)

desktop_packages=(
  gnome-session
  gnome-shell
  gdm3
  gvfs
  gvfs-backends
  network-manager-gnome
  nautilus
  gnome-terminal
  gnome-tweaks
  gnome-text-editor
  gnome-system-monitor
  xdg-desktop-portal-gnome
  fonts-cantarell
)


# Create fastfetch configuration
# Usage: setup_fastfetch
# Returns: 0 on success, 1 on failure
setup_fastfetch() {
	local fastfetch_dir="$HOME/.config/fastfetch"
	local config_file="$fastfetch_dir/config.jsonc"
	
	logger info "setting up fastfetch configuration..."
	
	# Create directory if it doesn't exist
	if [ ! -d "$fastfetch_dir" ]; then
		mkdir -p "$fastfetch_dir" || {
			logger error "failed to create fastfetch directory"
			return 1
		}
	fi
	
	# Create the configuration file
	cat > "$config_file" << 'EOF'
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "data",
    "source": "\u001b[97m  ▄▀▄▀▀▀▀▄▀▄\n  █        ▀▄      ▄\n █  ▀  ▀     ▀▄▄  █ █\n █ ▄ █▀ ▄       ▀▀  █\n █  ▀▀▀▀            █\n █                  █\n █                  █\n  █  ▄▄  ▄▄▄▄  ▄▄  █\n  █ ▄▀█ ▄▀  █ ▄▀█ ▄▀\n   ▀   ▀     ▀   ▀\u001b[0m",
    "padding": {
      "top": 1,
      "left": 1
    }
  },
  "display": {
    "color": {
      "keys": "90",
      "title": "90"
    }
  },
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "wm",
    "terminal",
    "cpu",
    "gpu",
    "memory",
    "swap",
    "disk",
    "localip",
    "battery",
    "locale"
  ]
}
EOF
	
	if [ $? -eq 0 ]; then
		logger done "fastfetch configuration created"
		return 0
	else
		logger error "failed to create fastfetch configuration"
		return 1
	fi
}


install_must_have_packages() {
  logger info "Installing must-have packages..."
  apt install -y "${must_have_packages[@]}"
}

install_desktop_packages() {
  if [[ "$INSTALL_DESKTOP" == "y" ]]; then
    logger info "Installing desktop packages..."
    
    apt install -y --no-install-recommends \
      gnome-session gnome-shell gdm3 gvfs gvfs-backends \
      network-manager-gnome nautilus gnome-terminal gnome-tweaks \
      gnome-text-editor gnome-system-monitor xdg-desktop-portal-gnome \
      fonts-cantarell

    curl -fsS https://dl.brave.com/install.sh | sh
  else
    logger info "Skipping desktop install."
  fi
}


# Check if the script is running as root
# Returns 0 if yes, 1 otherwise
is_running_as_root() {
  if [ "$(id -u)" -eq 0 ]; then
    return 0
  else
    return 1 
  fi
}

# Get the real user who invoked the script, even if run with sudo or pkexec
get_real_user() {
  # Priority order (best to worst)
  if [ -n "${SUDO_USER:-}" ]; then
    echo "$SUDO_USER"
  elif [ -n "${PKEXEC_UID:-}" ]; then
    id -un "$PKEXEC_UID"
  elif [ -n "${ORIGINAL_USER:-}" ]; then
    echo "$ORIGINAL_USER"
  else
    # Fallback
    echo "${USER:-$(whoami)}"
  fi
}

# Setup sudoers for the target user if not root
setup_sudoers() {
  local users=("$@")  # Accept all arguments as array

  # If no arguments provided, use current user
  if [ ${#users[@]} -eq 0 ]; then
    users=("$USER")
  fi

  for user in "${users[@]}"; do
    if [ -z "$user" ] || [ "$user" = "root" ]; then
      echo "Skipping root or empty username."
      continue
    fi

    echo "Setting up passwordless sudo for user: $user"

    cat > "/etc/sudoers.d/99-${user}-nopasswd" << EOF
$user ALL=(ALL) NOPASSWD:ALL
EOF

    chmod 0440 "/etc/sudoers.d/99-${user}-nopasswd"
    /usr/sbin/visudo -cf "/etc/sudoers.d/99-${user}-nopasswd" || {
      echo "Error: Failed to validate sudoers file for $user"
      rm -f "/etc/sudoers.d/99-${user}-nopasswd"
      return 1
    }
  done

  echo "Sudoers setup completed for: ${users[*]}"
}

# Logger object with dot notation methods
# Usage: logger <method> <message>
# Methods: info, done, error, warn
logger() {
	local method="$1"
	local message="$2"
	
	case "$method" in
		"info")
			echo -e "\033[44m INFO \033[0m $message"
			;;
		"done")
			echo -e "\033[42m DONE \033[0m $message"
			;;
		"error")
			echo -e "\033[41m ERROR \033[0m $message"
			;;
		"warn")
			echo -e "\033[43m WARN \033[0m $message"
			;;
		*)
			echo "Unknown logger method: $method"
			return 1
			;;
	esac
}

# Display a prompt and get a yes/no answer from the user.
# Usage: confirm "Prompt message" | confirm "Prompt message" "Y" | confirm "Prompt message" "N"
# Returns: 0 for yes, 1 for no
confirm() {
  local prompt="$1"
  local default="${2:-}"  # Optional: "Y" or "N"
  local answer

  while true; do
    if [ "$default" = "Y" ] || [ "$default" = "y" ]; then
      read -rp "$prompt [Y/n]: " answer
    elif [ "$default" = "N" ] || [ "$default" = "n" ]; then
      read -rp "$prompt [y/N]: " answer
    else
      read -rp "$prompt [y/n]: " answer
    fi

    answer="${answer,,}"  # to lowercase

    case "$answer" in
      y|yes) return 0 ;;
      n|no)  return 1 ;;
      "") 
        # Enter pressed - use default if set
        if [ "$default" = "Y" ] || [ "$default" = "y" ]; then
          return 0
        elif [ "$default" = "N" ] || [ "$default" = "n" ]; then
          return 1
        else
          echo "Please answer y or n."
        fi
        ;;
      *) echo "Please answer y or n." ;;
    esac
  done
}


is_running_as_root || { logger error "Run this script as root (or via su -c)."; exit 1; }

logger info "Starting installation script..."
confirm "Install minimal desktop apps (GNOME + Brave)?" && INSTALL_DESKTOP="y" || INSTALL_DESKTOP="n"
apt update
install_must_have_packages
setup_fastfetch
setup_sudoers "$(get_real_user)"
install_desktop_packages
logger done "Done."
confirm "Reboot now?" "Y" && logger info 'running sudo reboot now' && sudo reboot now || logger info "Reboot later to apply changes."

